/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projecteuler.problems;

/**
 *
 * @author Branimir
 */
public class Problem2 implements ProjectEulerProblem {
    int n;
    public Problem2() {
        n = 4000000; //upper limit
    }

    @Override
    public String description() {
        return "Problem 2: Even Fibonacci numbers\n"
                + "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n"
                + "\n"
                + "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
                + "\n"
                + "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
    }  

    @Override
    public String solve() {
        int sum = 0;
        int x1=1, x2=2;
        
        while(x2<=n) {
            if(x2%2==0)
                sum+=x2;
            x2 = x1 + x2;
            x1 = x2 - x1;
        }
        return String.valueOf(sum);
    }  
}
